export const organizationTestData = [
  {
    name: "Missing email field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Company name",
        state: "California",
        city: "Cansas",
        street: "Some street",
        postalCode: "26543",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing postal code field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Company name",
        state: "California",
        city: "Cansas",
        street: "Some street",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing street field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Company name",
        state: "California",
        city: "Cansas",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing city field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Company name",
        state: "California",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing state field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Company name",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing name field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId,
        licenseFilesIds: [],
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing country id field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        licenseFilesIds: [],
        name: "Some company",
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing region id field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        countryId,
        licenseFilesIds: [],
        name: "Some company",
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Missing id field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Some company",
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "ERR002",
    }),
  },
  {
    name: "Empty id field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: "",
        regionId,
        countryId,
        licenseFilesIds: [],
        name: "Some company",
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "id must be a UUID",
    }),
  },
  {
    name: "Empty region id field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId: "",
        countryId,
        licenseFilesIds: [],
        name: "Some company",
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "regionId must be a UUID",
    }),
  },
  {
    name: "Empty country id field",
    getData: (orgId: string, regionId: string, countryId: string) => ({
      params: {
        id: orgId,
        regionId,
        countryId: "",
        licenseFilesIds: [],
        name: "Some company",
        state: "California",
        city: "Some street",
        street: "Some street",
        postalCode: "32453",
        email: "semeEmail@company.com",
      },
      expectedMessage: "countryId must be a UUID",
    }),
  },
];
