export const invalidEmails: (string | null | undefined)[] = [
  "plainaddress",
  "@missingusername.com",
  "missingatsign.com",
  "missingdomain@.com",
  "missingdot@domain",
  "user@domain..com",
  "user@-domain.com",
  "user@domain-.com",
  "user@domain.c",
  "user@.domain.com",
  "user@domain space.com",
  "user@domain,com",
  "user@domain@domain.com",
  "user@domain#mail.com",
  "",
  "   ",
  null,
  undefined,
];